spring.application.name=Order Returns System

# Server (use 127.0.0.1:8080 if localhost fails on Windows)
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/returnsdb
spring.data.mongodb.auto-index-creation=true

# Thymeleaf
spring.thymeleaf.cache=false
